name: DNS
on:
  push:
    branches:
      - dev
      - prod                                    
      - staging
    paths:
      - 'Network/DNS/**'
  workflow_dispatch:
    inputs: 
      dns_storage_account_rg_name:
        description: rg name for dns tf state storage account  
        type: string
        required: true
      dns_storage_account_name:
        description: dns tf state storage account name 
        type: string
        required: true
      dns_storage_account_container_name:
        description: aks tf state storage account container name 
        type: string
        required: true
      dns_storage_account_key:
        description: dns tfstate filename 
        type: string
        required: true  
    #   rg_tf_state_rg_name:
    #     description: rg name for resource group tf state storage account  
    #     type: string
    #     required: true
    #   rg_tf_state_storage_account_name:
    #     description: resource group tf state storage account name 
    #     type: string
    #     required: true      	
    #   rg_tf_state_container_name:
    #     description: container name for resource group tf state storage account 
    #     type: string
    #     required: true
    #   rg_tf_state_key:
    #     description: resource group tfstate filename 
    #     type: string
    #     required: true   	
    #   dns_zone_name:
    #     description: dns name
    #     type: string
    #     required: true
defaults:
  run:
    shell: bash

permissions:
  id-token: write
  contents: read
  pull-requests: write
    
env:
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
  ARM_CLIENT_SECRET: "${{ secrets.AZURE_CLIENT_SECRET }}"

jobs:
  deploy_dns:
    name: 'deploy_dns'
    runs-on: ['self-hosted','infrastructure']
    defaults:
      run:
        shell: bash
        working-directory: ./Network/DNS
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Set environment folder based on branch
        id: set_env_folder
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            ENV_FOLDER="Development"
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            ENV_FOLDER="Staging"
          elif [[ "${{ github.ref }}" == "refs/heads/prod" ]]; then
            ENV_FOLDER="Production"
          else
            echo "Branch not recognized"
            exit 1
          fi
          echo "ENV_FOLDER=$ENV_FOLDER" >> $GITHUB_ENV

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.4

      - name: Azure CLI script
        uses: pietrobolcato/install-azure-cli-action@main
        
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Use an LTS version of Node.js
  
      - name: Terraform Init
        run: |
          export AZURE_SUBSCRIPTION_ID=$ARM_SUBSCRIPTION_ID
          cd ${{ env.ENV_FOLDER }}
          terraform init -backend-config="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
                         -backend-config="tenant_id=${{ secrets.AZURE_TENANT_ID }}" \
                         -backend-config="client_id=${{ secrets.AZURE_CLIENT_ID }}" \
                         -backend-config="resource_group_name=${{ inputs.dns_storage_account_rg_name }}" \
                         -backend-config="storage_account_name=${{ inputs.dns_storage_account_name }}" \
                         -backend-config="container_name=${{ inputs.dns_storage_account_container_name }}" \
                         -backend-config="key=${{ inputs.dns_storage_account_key }}" \
                         -backend-config="client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" 


      - name: Terraform Validate
        run: |
          cd ${{ env.ENV_FOLDER }}
          terraform validate 

      - name: Terraform Plan
        run: |
          terraform -chdir=Staging plan \
            -var "AZURE_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
            -var "tenant_id=${{ secrets.AZURE_TENANT_ID }}" \
            -var "client_id=${{ secrets.AZURE_CLIENT_ID }}" \
            -var "client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" \
            -var-file="dns.tfvars" -lock=false
                     

      - name: Terraform Apply
        run: |
          terraform -chdir=Staging apply -auto-approve  -var "AZURE_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
                                                                      -var "tenant_id=${{ secrets.AZURE_TENANT_ID }}" \
                                                                      -var "client_id=${{ secrets.AZURE_CLIENT_ID }}" \
                                                                      -var "client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" \
                                                                      -var-file="dns.tfvars" -lock=false
      - name: Terraform output
        run: |
          cd ${{ env.ENV_FOLDER }}
          terraform output 
