name: Resource_Group

on:
  push:
    branches:
      - dev
      - prod
      - staging
    paths:
        - 'Resource_Group/**'
  workflow_dispatch:
    inputs: 
      rg_name:
        description: 'resource group name'     
        required: true
        type: string

defaults:
  run:
    shell: bash

permissions:
  id-token: write
  contents: read
  pull-requests: write
    
env:
  ARM_SUBSCRIPTION_ID: "${{ secrets.AZURE_SUBSCRIPTION_ID }}"
  ARM_TENANT_ID: "${{ secrets.AZURE_TENANT_ID }}"
  ARM_CLIENT_ID: "${{ secrets.AZURE_CLIENT_ID }}"
  ARM_CLIENT_SECRET: "${{ secrets.AZURE_CLIENT_SECRET }}"

jobs:
  deploy_rg:
    name: 'Terraform init-plan-apply-for-resource-groupe'
    runs-on: ubuntu-latest 
    defaults:
      run:
        shell: bash
        working-directory: ./Resource_Group

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set environment folder based on branch
        id: set_env_folder
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            ENV_FOLDER="Development"
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            ENV_FOLDER="Staging"
          elif [[ "${{ github.ref }}" == "refs/heads/prod" ]]; then
            ENV_FOLDER="Production"
          else
            echo "Branch not recognized"
            exit 1
          fi
          echo "ENV_FOLDER=$ENV_FOLDER" >> $GITHUB_ENV
      
      - name: Download Terraform
        run: |
          wget https://releases.hashicorp.com/terraform/1.5.4/terraform_1.5.4_linux_amd64.zip
          unzip terraform_1.5.4_linux_amd64.zip
          sudo mv terraform /usr/local/bin/

      - name: Azure CLI script
        uses: pietrobolcato/install-azure-cli-action@main

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: |
          cd ${{ env.ENV_FOLDER }}
          terraform init -backend-config="subscription_id=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
                         -backend-config="tenant_id=${{ secrets.AZURE_TENANT_ID }}" \
                         -backend-config="client_id=${{ secrets.AZURE_CLIENT_ID }}" \
                         -backend-config="client_secret=${{ secrets.AZURE_CLIENT_SECRET }}"

      - name: Terraform Validate
        run: |
          cd ${{ env.ENV_FOLDER }}
          terraform validate 

      - name: Terraform Plan
        run: |
          cd ${{ env.ENV_FOLDER }}
          terraform plan -var "AZURE_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
                         -var "tenant_id=${{ secrets.AZURE_TENANT_ID }}" \
                         -var "client_id=${{ secrets.AZURE_CLIENT_ID }}" \
                         -var "client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" \
                         -var "resource_group_name=${{ inputs.rg_name }}" -lock=false

      - name: Terraform Apply
        run: | 
          cd ${{ env.ENV_FOLDER }}
          terraform apply -auto-approve -var "AZURE_SUBSCRIPTION_ID=${{ secrets.AZURE_SUBSCRIPTION_ID }}" \
                          -var "tenant_id=${{ secrets.AZURE_TENANT_ID }}" \
                          -var "client_id=${{ secrets.AZURE_CLIENT_ID }}" \
                          -var "client_secret=${{ secrets.AZURE_CLIENT_SECRET }}" \
                          -var "resource_group_name=${{ inputs.rg_name }}" -lock=false

      - name: Terraform Output
        run: | 
          cd ${{ env.ENV_FOLDER }}
          terraform output
